### ISSUE TITLE
这个东西可以挂到GitHub actions自动执行吗

### ISSUE THREAD

**Issue by zsqw123** [JLUZHAnalytica/Automatic-Health-Card#2]
这个东西可以挂到GitHub actions自动执行吗, 顺便配合server酱通知, 我去试试(

**Comment by zsqw123** [comment]
我自己搞好了(

**Comment by VidocqH** [comment]
谢谢提醒，现在[我的fork](https://github.com/VidocqH/Automatic-Health-Card)可用actions了😂不过没有弄server酱，区间签到的话日志会超出server酱的大小限制

[这个js版本](https://github.com/ArchFireCoo/AutoHealthCard)有server酱，支持并发 ~~学校服务器体操😂~~

**Comment by zsqw123** [comment]
> 谢谢提醒，现在[我的fork](https://github.com/VidocqH/Automatic-Health-Card)可用actions了😂不过没有弄server酱，区间签到的话日志会超出server酱的大小限制
> 
> [这个js版本](https://github.com/ArchFireCoo/AutoHealthCard)有server酱，支持并发 ~学校服务器体操😂~

哈哈哈其实我不是你们学校的, 只是我们学校系统和这个类似, 我已经改成[我们学校的版本了](https://github.com/zsqw123/Automatic-Health-Card)
